package POJOS;
// Generated Jan 27, 2021 3:30:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private Integer iddoctor;
     private User user;
     private String name;
     private String contactNumber;
     private String regNumber;
     private String note;
     private Integer status;
     private Set prescriptions = new HashSet(0);

    public Doctor() {
    }

	
    public Doctor(User user) {
        this.user = user;
    }
    public Doctor(User user, String name, String contactNumber, String regNumber, String note, Integer status, Set prescriptions) {
       this.user = user;
       this.name = name;
       this.contactNumber = contactNumber;
       this.regNumber = regNumber;
       this.note = note;
       this.status = status;
       this.prescriptions = prescriptions;
    }
   
    public Integer getIddoctor() {
        return this.iddoctor;
    }
    
    public void setIddoctor(Integer iddoctor) {
        this.iddoctor = iddoctor;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }
    public String getRegNumber() {
        return this.regNumber;
    }
    
    public void setRegNumber(String regNumber) {
        this.regNumber = regNumber;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getPrescriptions() {
        return this.prescriptions;
    }
    
    public void setPrescriptions(Set prescriptions) {
        this.prescriptions = prescriptions;
    }




}


