package POJOS;
// Generated Jan 19, 2021 12:56:26 AM by Hibernate Tools 4.3.1



/**
 * PrescriptionItem generated by hbm2java
 */
public class PrescriptionItem  implements java.io.Serializable {


     private Integer idprescriptionItem;
     private MealType mealType;
     private Prescription prescription;
     private Stock stock;
     private UseCycle useCycle;
     private UseMethod useMethod;
     private Double dosage;
     private Double duration;
     private Double qty;
     private Double costPerItem;
     private Double totalCost;
     private String remark;
     private Integer status;

    public PrescriptionItem() {
    }

	
    public PrescriptionItem(MealType mealType, Prescription prescription, Stock stock, UseCycle useCycle, UseMethod useMethod) {
        this.mealType = mealType;
        this.prescription = prescription;
        this.stock = stock;
        this.useCycle = useCycle;
        this.useMethod = useMethod;
    }
    public PrescriptionItem(MealType mealType, Prescription prescription, Stock stock, UseCycle useCycle, UseMethod useMethod, Double dosage, Double duration, Double qty, Double costPerItem, Double totalCost, String remark, Integer status) {
       this.mealType = mealType;
       this.prescription = prescription;
       this.stock = stock;
       this.useCycle = useCycle;
       this.useMethod = useMethod;
       this.dosage = dosage;
       this.duration = duration;
       this.qty = qty;
       this.costPerItem = costPerItem;
       this.totalCost = totalCost;
       this.remark = remark;
       this.status = status;
    }
   
    public Integer getIdprescriptionItem() {
        return this.idprescriptionItem;
    }
    
    public void setIdprescriptionItem(Integer idprescriptionItem) {
        this.idprescriptionItem = idprescriptionItem;
    }
    public MealType getMealType() {
        return this.mealType;
    }
    
    public void setMealType(MealType mealType) {
        this.mealType = mealType;
    }
    public Prescription getPrescription() {
        return this.prescription;
    }
    
    public void setPrescription(Prescription prescription) {
        this.prescription = prescription;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public UseCycle getUseCycle() {
        return this.useCycle;
    }
    
    public void setUseCycle(UseCycle useCycle) {
        this.useCycle = useCycle;
    }
    public UseMethod getUseMethod() {
        return this.useMethod;
    }
    
    public void setUseMethod(UseMethod useMethod) {
        this.useMethod = useMethod;
    }
    public Double getDosage() {
        return this.dosage;
    }
    
    public void setDosage(Double dosage) {
        this.dosage = dosage;
    }
    public Double getDuration() {
        return this.duration;
    }
    
    public void setDuration(Double duration) {
        this.duration = duration;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getCostPerItem() {
        return this.costPerItem;
    }
    
    public void setCostPerItem(Double costPerItem) {
        this.costPerItem = costPerItem;
    }
    public Double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


