package POJOS;
// Generated Apr 20, 2021 10:27:05 PM by Hibernate Tools 4.3.1



/**
 * PrescriptionItem generated by hbm2java
 */
public class PrescriptionItem  implements java.io.Serializable {


     private Integer idprescriptionItem;
     private MealType mealType;
     private MedicineType medicineType;
     private Prescription prescription;
     private Stock stock;
     private UseCycle useCycle;
     private UseMethod useMethod;
     private String dosage;
     private Double duration;
     private Double qty;
     private Double unitCost;
     private Double totalCost;
     private Double unitPrice;
     private Double totalPrice;
     private String remark;
     private Integer status;

    public PrescriptionItem() {
    }

	
    public PrescriptionItem(MealType mealType, MedicineType medicineType, Prescription prescription, Stock stock, UseCycle useCycle, UseMethod useMethod) {
        this.mealType = mealType;
        this.medicineType = medicineType;
        this.prescription = prescription;
        this.stock = stock;
        this.useCycle = useCycle;
        this.useMethod = useMethod;
    }
    public PrescriptionItem(MealType mealType, MedicineType medicineType, Prescription prescription, Stock stock, UseCycle useCycle, UseMethod useMethod, String dosage, Double duration, Double qty, Double unitCost, Double totalCost, Double unitPrice, Double totalPrice, String remark, Integer status) {
       this.mealType = mealType;
       this.medicineType = medicineType;
       this.prescription = prescription;
       this.stock = stock;
       this.useCycle = useCycle;
       this.useMethod = useMethod;
       this.dosage = dosage;
       this.duration = duration;
       this.qty = qty;
       this.unitCost = unitCost;
       this.totalCost = totalCost;
       this.unitPrice = unitPrice;
       this.totalPrice = totalPrice;
       this.remark = remark;
       this.status = status;
    }
   
    public Integer getIdprescriptionItem() {
        return this.idprescriptionItem;
    }
    
    public void setIdprescriptionItem(Integer idprescriptionItem) {
        this.idprescriptionItem = idprescriptionItem;
    }
    public MealType getMealType() {
        return this.mealType;
    }
    
    public void setMealType(MealType mealType) {
        this.mealType = mealType;
    }
    public MedicineType getMedicineType() {
        return this.medicineType;
    }
    
    public void setMedicineType(MedicineType medicineType) {
        this.medicineType = medicineType;
    }
    public Prescription getPrescription() {
        return this.prescription;
    }
    
    public void setPrescription(Prescription prescription) {
        this.prescription = prescription;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public UseCycle getUseCycle() {
        return this.useCycle;
    }
    
    public void setUseCycle(UseCycle useCycle) {
        this.useCycle = useCycle;
    }
    public UseMethod getUseMethod() {
        return this.useMethod;
    }
    
    public void setUseMethod(UseMethod useMethod) {
        this.useMethod = useMethod;
    }
    public String getDosage() {
        return this.dosage;
    }
    
    public void setDosage(String dosage) {
        this.dosage = dosage;
    }
    public Double getDuration() {
        return this.duration;
    }
    
    public void setDuration(Double duration) {
        this.duration = duration;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getUnitCost() {
        return this.unitCost;
    }
    
    public void setUnitCost(Double unitCost) {
        this.unitCost = unitCost;
    }
    public Double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


