package POJOS;
// Generated Jan 27, 2021 12:48:16 PM by Hibernate Tools 4.3.1



/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private Integer idvehicle;
     private String name;
     private String number;
     private Integer status;

    public Vehicle() {
    }

    public Vehicle(String name, String number, Integer status) {
       this.name = name;
       this.number = number;
       this.status = status;
    }
   
    public Integer getIdvehicle() {
        return this.idvehicle;
    }
    
    public void setIdvehicle(Integer idvehicle) {
        this.idvehicle = idvehicle;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


